name: build

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild and .NET Framework
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: msbuild "UAC白名单小工具.sln" /p:Configuration=Release

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: "./UAC白名单小工具/bin/Release/*" 
